FROM alpine:edge
MAINTAINER Jermine.hu@qq.com
WORKDIR /app
RUN set -xe ;\
         apk add --no-cache curl python3 gcc g++ libc-dev musl-dev binutils ;\
         curl -sSL https://bootstrap.pypa.io/get-pip.py | python3 ;\
         pip3 -V
        
RUN pip3 install tensorflow
