FROM alpine:edge
MAINTAINER Jermine.hu@qq.com
WORKDIR /app
RUN set -xe ;\
         apk add --no-cache curl python3 gcc g++ libc-dev musl-dev binutils ;\
         curl -sSL https://bootstrap.pypa.io/get-pip.py | python3 ;\
         pip3 -V
        
RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.5.0-cp36-cp36m-linux_x86_64.whl
